In [3]:
import numpy as np

In [4]:
# 2.1
x_0 = np.zeros(5)
print(x_0)
x_1 = np.ones(10)
print(x_1)
x_2 = np.full(5, 3.141)
print(x_2)
x_3 = np.arange(1,20)
print(x_3)
x_4 = np.full((5,5),0, dtype=int)
print(x_4)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3.141 3.141 3.141 3.141 3.141]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [6]:
#2.2
x = np.random.randn(3, 3, 3)
print(x)
print('reshape: \n', x.reshape(27,))

[[[ 0.53238081 -1.40605062 -0.31490276]
  [-0.38501386 -0.83252348  1.08516529]
  [-0.89009488  1.07998264  1.35736282]]

 [[-0.70296738  0.45527348  0.42335704]
  [-0.36596053  1.50540704  0.06631331]
  [ 0.45246978  0.26116716  2.58754463]]

 [[ 0.50040338  0.77223704 -1.11284184]
  [-1.22236359 -2.21918139  0.25731131]
  [-0.05248113  0.72241372  2.16749242]]]
reshape: 
 [ 0.53238081 -1.40605062 -0.31490276 -0.38501386 -0.83252348  1.08516529
 -0.89009488  1.07998264  1.35736282 -0.70296738  0.45527348  0.42335704
 -0.36596053  1.50540704  0.06631331  0.45246978  0.26116716  2.58754463
  0.50040338  0.77223704 -1.11284184 -1.22236359 -2.21918139  0.25731131
 -0.05248113  0.72241372  2.16749242]


In [5]:
#2.3
x = np.linspace(1,10,20)
print(x)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [8]:
#2.4
x = np.random.randn(6,6)
print(x[0:3,:])

print(x[[0,1,5],:])

print(x[:,0:3])

print(x[:,[0,1,3]])

print(x[[2,3],0:3])

print(x[1::2,0::2])

[[-0.77682553  0.08467133 -0.14753958 -2.36047846 -1.28640695 -1.16796095]
 [ 0.02784796  1.40118455 -0.80899855  2.04750051 -1.03760267  0.59607415]
 [ 0.20255758 -1.25322685  0.83630487  0.27653717  1.03797989 -0.03894158]]
[[-0.77682553  0.08467133 -0.14753958 -2.36047846 -1.28640695 -1.16796095]
 [ 0.02784796  1.40118455 -0.80899855  2.04750051 -1.03760267  0.59607415]
 [ 1.42308246 -0.04095375  0.58405989  0.06508868  0.77195824  0.40113953]]
[[-0.77682553  0.08467133 -0.14753958]
 [ 0.02784796  1.40118455 -0.80899855]
 [ 0.20255758 -1.25322685  0.83630487]
 [ 1.22456126  0.26579974  0.14463966]
 [ 0.07053732  1.01893915  1.25030553]
 [ 1.42308246 -0.04095375  0.58405989]]
[[-0.77682553  0.08467133 -2.36047846]
 [ 0.02784796  1.40118455  2.04750051]
 [ 0.20255758 -1.25322685  0.27653717]
 [ 1.22456126  0.26579974 -0.16822072]
 [ 0.07053732  1.01893915 -0.80052273]
 [ 1.42308246 -0.04095375  0.06508868]]
[[ 0.20255758 -1.25322685  0.83630487]
 [ 1.22456126  0.26579974  0.14463966]]

In [10]:
#2.5
x = np.zeros((5,5))
x[1:-1:,1:-1:]= 1
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
#2.6
a = np.arange(1,26).reshape(5,-1)
print(a)
print('-'*30)
print(a[1::,-2::])
print('-'*30)
print(a[1,:])
print('-'*30)
print(a[2:4,:])
print('-'*30)
print(a[1:3,2:4])
print('-'*30)
print('Sum of all numbers:', np.sum(a))
print('-'*30)
print('Sum of each row:', np.sum(a, axis=1))
print('-'*30)
print(f'All value greater than mean of a: mean a = {a.mean()}\n value:', a[a>a.mean()])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
------------------------------
[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]
------------------------------
[ 6  7  8  9 10]
------------------------------
[[11 12 13 14 15]
 [16 17 18 19 20]]
------------------------------
[[ 8  9]
 [13 14]]
------------------------------
Sum of all numbers: 325
------------------------------
Sum of each row: [ 15  40  65  90 115]
------------------------------
All value greater than mean of a: mean a = 13.0
 value: [14 15 16 17 18 19 20 21 22 23 24 25]


In [19]:
#2.7
X = np.array([[ 1, -5, 6, -1, 0],
            [ 5, 2, 0, 4, -2],
            [-7, -7, 1, -8, 4],
            [-5, 7, 2, -9, 5],
            [ 5, 3, 0, 2, 1],
            [ 0, 6, 4, 0, 2]])
print(X)
print('Shape:',X.shape)
print('3rd row, 4th col element:',X[1,3])
print('6th row, 1st col element:',X[5,0])
print('5th row, 2nd col element:',X[4,1])

[[ 1 -5  6 -1  0]
 [ 5  2  0  4 -2]
 [-7 -7  1 -8  4]
 [-5  7  2 -9  5]
 [ 5  3  0  2  1]
 [ 0  6  4  0  2]]
Shape: (6, 5)
3rd row, 4th col element: 4
6th row, 1st col element: 0
5th row, 2nd col element: 3


In [22]:
#2.8
np.random.seed(123)
b = np.random.randn(10)
b
print('Location of min value:',np.argmin(b),"value:",[b[np.argmin(b)]])

Location of min value: 6 value: [np.float64(-2.426679243393074)]


In [27]:
#2.9
x = np.random.rand(10,3)
print(x)
closest_to_0_5 = x[np.abs(x-0.5).argmin(axis=0)]
print('Closest to 0.5:', closest_to_0_5)
selected_elements = a[[0, 1, 2], [2, 3, 1]]
print('Selected elements:', selected_elements)

[[0.60069857 0.86586446 0.98352161]
 [0.07936579 0.42834727 0.20454286]
 [0.45063649 0.54776357 0.09332671]
 [0.29686078 0.92758424 0.56900373]
 [0.457412   0.75352599 0.74186215]
 [0.04857903 0.7086974  0.83924335]
 [0.16593788 0.78099794 0.28653662]
 [0.30646975 0.66526147 0.11139217]
 [0.66487245 0.88785679 0.69631127]
 [0.44032788 0.43821438 0.7650961 ]]
Closest to 0.5: [[0.457412   0.75352599 0.74186215]
 [0.45063649 0.54776357 0.09332671]
 [0.29686078 0.92758424 0.56900373]]
Selected elements: [ 3  9 12]


In [29]:
#2.11
np_array = [[45, 61, 65, 44, 1, 18],
        [7, 4, 58, 58, 66, 78],
        [16, 95, 39, 1, 90, 33],
        [40, 41, 79, 67, 40, 86]]
print(np_array)
print('Min value for rows:', np.min(np_array, axis=1))
print('Min value for columns:', np.min(np_array, axis=0))
print('Max value for rows:', np.max(np_array, axis=1))
print('Max value for columns:', np.max(np_array, axis=0))
print('Min value of ARRAY:', np.min(np_array))
print('Max value of ARRAY:', np.max(np_array))
print('Mean value for rows:', np.mean(np_array, axis=1))
print('Mean value for columns:', np.mean(np_array, axis=0))
print('Mean value of ARRAY:', np.mean(np_array))
print('StDeviation value for rows:', np.std(np_array, axis=1))
print('StDeviation value for columns:', np.std(np_array, axis=0))
print('StDeviation value of ARRAY:', np.std(np_array))
print('Variance value for rows:', np.var(np_array, axis=1))
print('Variance value for columns:', np.var(np_array, axis=0))
print('Variance value of ARRAY:', np.var(np_array))

[[45, 61, 65, 44, 1, 18], [7, 4, 58, 58, 66, 78], [16, 95, 39, 1, 90, 33], [40, 41, 79, 67, 40, 86]]
Min value for rows: [ 1  4  1 40]
Min value for columns: [ 7  4 39  1  1 18]
Max value for rows: [65 78 95 86]
Max value for columns: [45 95 79 67 90 86]
Min value of ARRAY: 1
Max value of ARRAY: 95
Mean value for rows: [39.         45.16666667 45.66666667 58.83333333]
Mean value for columns: [27.   50.25 60.25 42.5  49.25 53.75]
Mean value of ARRAY: 47.166666666666664
StDeviation value for rows: [22.75228926 28.84681766 35.30659366 19.31680328]
StDeviation value for columns: [15.92168333 32.94977238 14.41136704 25.32291452 32.99526481 28.88230427]
StDeviation value of ARRAY: 28.18933998675543
Variance value for rows: [ 517.66666667  832.13888889 1246.55555556  373.13888889]
Variance value for columns: [ 253.5    1085.6875  207.6875  641.25   1088.6875  834.1875]
Variance value of ARRAY: 794.6388888888888


In [31]:
#2.12
def compare_arrays(arr1, arr2):
    if arr1.shape != arr2.shape:
        raise ValueError("Both arrays must have the same shape")
    return np.where(arr1 == arr2, True, False)

arr1 = np.array([10, 20, 30])
arr2 = np.array([10, 30, 30])
result = compare_arrays(arr1, arr2)
print(result)  

[ True False  True]


In [32]:
#2.13
def find_equal_indices(arr1, arr2):
    if arr1.shape != arr2.shape:
        raise ValueError("Both arrays must have the same shape")
    return np.where(arr1 == arr2)[0]

# Example usage:
arr1 = np.array([10, 20, 30])
arr2 = np.array([10, 30, 30])
result = find_equal_indices(arr1, arr2)
print(result)  # Output: [0 2]

[0 2]


In [36]:
#2.14
def clip_values(arr, min_val=None, max_val=None):
    # Create a copy of the array to avoid modifying the input array
    clipped_arr = np.copy(arr)
    
    # Apply clipping based on provided min_val and max_val
    if min_val is not None:
        clipped_arr = np.maximum(clipped_arr, min_val)
    if max_val is not None:
        clipped_arr = np.minimum(clipped_arr, max_val)
    
    return clipped_arr

# Example usage:
arr1 = np.array([1, 2, 3])
result1 = clip_values(arr1, min_val=2)
print(result1)  # Output: [2 2 3]

arr2 = np.array([1, 2, 3])
result2 = clip_values(arr2, max_val=2)
print(result2)  # Output: [1 2 2]

[2 2 3]
[1 2 2]


In [34]:
#2.15
A = np.array([[2, -1, 1],
            [3, 3, 9],
            [3, 3, 5]])

# Define the right-hand side vector b
b = np.array([-1, 0, 4])

# Solve the linear system
x = np.linalg.solve(A, b)

print("Solution x:", x)

Solution x: [ 1.  2. -1.]


In [37]:
#2.16
# Define the coefficient matrix A
A = np.array([[2, -1, 1],
            [3, 3, 9],
            [3, 3, 5]])

# Define the right-hand side vector b
b = np.array([-1, 0, 4])

# Solve the linear system
x = np.linalg.solve(A, b)

# Calculate the difference vector d = Ax - b
d = np.dot(A, x) - b

# Calculate the Euclidean norm of the difference vector
norm_d = np.linalg.norm(d)

print("Difference vector d:", d)
print("Euclidean norm of the difference vector |d|:", norm_d)

Difference vector d: [0. 0. 0.]
Euclidean norm of the difference vector |d|: 0.0


In [38]:
#2.17

def add_row(A, s, i, j):
    A_new = np.copy(A)
    A_new[j] += s * A_new[i]
    return A_new
# Example usage:
A = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])

s = 2
i = 0
j = 1

result = add_row(A, s, i, j)
print(result)

[[ 1  2  3]
 [ 6  9 12]
 [ 7  8  9]]


In [39]:
#2.18
def inverse_matrix(A):
    n = A.shape[0]
    augmented_matrix = np.hstack((A, np.eye(n)))
    
    for i in range(n):
        factor = augmented_matrix[i, i]
        augmented_matrix[i] = augmented_matrix[i] / factor
        
        for j in range(n):
            if i != j:
                factor = augmented_matrix[j, i]
                augmented_matrix[j] = augmented_matrix[j] - factor * augmented_matrix[i]
    
    inverse_A = augmented_matrix[:, n:]
    
    return inverse_A

# Example usage:
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])

inverse_A = inverse_matrix(A)
print("Inverse of A:\n", inverse_A)

Inverse of A:
 [[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]


In [43]:
#2.19
def qr_decomposition(matrix):
    Q, R = np.linalg.qr(matrix)
    return Q, R

# Example usage:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Q, R = qr_decomposition(A)
print("Matrix Q:\n", Q)
print("Matrix R:\n", R)

Matrix Q:
 [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
Matrix R:
 [[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [44]:
#2.20
def sum_of_diagonal_elements(matrix):
    return np.trace(matrix)

# Example usage:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

sum_diagonal = sum_of_diagonal_elements(A)
print("Sum of diagonal elements:", sum_diagonal)

Sum of diagonal elements: 15


In [45]:
#2.21
def compute_eigenvalues_and_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

# Example usage:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

eigenvalues, eigenvectors = compute_eigenvalues_and_eigenvectors(A)
print("Eigenvalues:\n", eigenvalues)
print("Right eigenvectors:\n", eigenvectors)

Eigenvalues:
 [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Right eigenvectors:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
